version: '3'

services:
  app:
    build: ./backend
    restart: always
    networks:
      - backend

  nginx:
    build: ./nginx
    restart: always
    networks:
      - app

networks:
  app:
    external:
      false


