version: '3'

services:
  backend:
    build: ./backend
    restart: always
    networks:
      - backend

  nginx:
    build: ./nginx
    restart: always
    networks:
      - backend

networks:
  backend:
    external:
      false


